// Static, curated set of daily coding challenges. Rotates deterministically by
// date (no AI calls, no quota risk, works offline) so every visitor sees the
// same "today's challenge" and it's stable across reloads/devices.

export const CHALLENGES = [
  { id: 'js-array-methods', title: 'JavaScript Array Methods', language: 'JavaScript', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Given an array of order totals, use map, filter, and reduce to return the total revenue from orders over $50.', solution: 'orders.filter(o => o > 50).reduce((sum, o) => sum + o, 0) — filter keeps only qualifying orders, reduce sums what remains.' },
  { id: 'py-list-comprehension', title: 'List Comprehensions', language: 'Python', difficulty: 'Easy', minutes: 10, xp: 80, coins: 20, prompt: 'Write a one-line list comprehension that returns the squares of all even numbers from 1 to 20.', solution: '[n**2 for n in range(1, 21) if n % 2 == 0] — the condition filters to evens before squaring.' },
  { id: 'css-flexbox-center', title: 'Perfect Centering with Flexbox', language: 'CSS', difficulty: 'Easy', minutes: 8, xp: 70, coins: 20, prompt: 'Center a div both horizontally and vertically inside its parent using only Flexbox.', solution: '.parent { display: flex; align-items: center; justify-content: center; } — two lines is all Flexbox needs.' },
  { id: 'js-closures', title: 'Understanding Closures', language: 'JavaScript', difficulty: 'Medium', minutes: 20, xp: 140, coins: 40, prompt: 'Write a `makeCounter()` function that returns an increment function, where each counter keeps its own private count.', solution: 'function makeCounter() { let n = 0; return () => ++n } — the inner function closes over `n`, giving every counter its own private state.' },
  { id: 'py-dict-merge', title: 'Merging Dictionaries', language: 'Python', difficulty: 'Easy', minutes: 8, xp: 70, coins: 20, prompt: 'Merge two dictionaries so keys in the second override the first, without mutating either input.', solution: '{**dict_a, **dict_b} — later spreads win on key collisions.' },
  { id: 'js-debounce', title: 'Build a Debounce Function', language: 'JavaScript', difficulty: 'Hard', minutes: 25, xp: 180, coins: 55, prompt: 'Implement a `debounce(fn, delay)` utility that only calls `fn` after `delay` ms have passed since the last call.', solution: 'Track a timeout id in closure; clearTimeout on every call, then setTimeout(fn, delay) again — resets the clock each call.' },
  { id: 'sql-join-basics', title: 'Inner Join Basics', language: 'SQL', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Write a query that returns each order alongside the customer name it belongs to, using an INNER JOIN.', solution: 'SELECT o.id, c.name FROM orders o JOIN customers c ON o.customer_id = c.id;' },
  { id: 'py-recursion-fib', title: 'Recursive Fibonacci', language: 'Python', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Write a recursive function that returns the nth Fibonacci number, then add memoization to avoid recomputation.', solution: 'Base case n<=1 returns n; otherwise return fib(n-1)+fib(n-2). Wrap with functools.lru_cache to memoize.' },
  { id: 'css-grid-layout', title: 'Responsive Card Grid', language: 'CSS', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Build a responsive grid that shows 1 column on mobile, 2 on tablet, and 3 on desktop, using CSS Grid only.', solution: 'grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); — auto-fit + minmax adapts columns to available width.' },
  { id: 'js-promise-all', title: 'Parallel Requests with Promise.all', language: 'JavaScript', difficulty: 'Medium', minutes: 18, xp: 130, coins: 38, prompt: 'Fetch three unrelated API endpoints in parallel and combine their results once all have resolved.', solution: 'const [a, b, c] = await Promise.all([fetch(url1), fetch(url2), fetch(url3)]) — runs all three concurrently instead of one after another.' },
  { id: 'py-generators', title: 'Lazy Sequences with Generators', language: 'Python', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Write a generator function that lazily yields an infinite sequence of prime numbers.', solution: 'Use `yield` inside a `while True` loop, testing primality incrementally — values are produced one at a time, on demand.' },
  { id: 'js-array-dedupe', title: 'Remove Duplicates from an Array', language: 'JavaScript', difficulty: 'Easy', minutes: 6, xp: 60, coins: 15, prompt: 'Given an array with duplicate values, return a new array with only unique values.', solution: '[...new Set(array)] — Set only stores unique values, spreading it back into an array.' },
  { id: 'ts-generics-intro', title: 'Generic Utility Function', language: 'TypeScript', difficulty: 'Medium', minutes: 18, xp: 130, coins: 38, prompt: 'Write a generic `first<T>(items: T[]): T | undefined` function that returns the first element of any typed array.', solution: 'function first<T>(items: T[]): T | undefined { return items[0] } — the generic <T> lets it work for any array type while staying type-safe.' },
  { id: 'py-string-palindrome', title: 'Palindrome Checker', language: 'Python', difficulty: 'Easy', minutes: 8, xp: 70, coins: 20, prompt: 'Write a function that checks if a string is a palindrome, ignoring case and spaces.', solution: 'cleaned = s.lower().replace(" ", ""); return cleaned == cleaned[::-1]' },
  { id: 'js-event-delegation', title: 'Event Delegation', language: 'JavaScript', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Attach a single click listener to a list container that identifies which `<li>` was clicked, without binding a listener to every item.', solution: "list.addEventListener('click', e => { const li = e.target.closest('li'); if (li) handle(li) }) — the parent listener inspects e.target." },
  { id: 'css-animations-keyframes', title: 'Custom Keyframe Animation', language: 'CSS', difficulty: 'Easy', minutes: 10, xp: 80, coins: 22, prompt: 'Create a pulsing animation that scales an element up and down continuously using @keyframes.', solution: '@keyframes pulse { 0%,100% { transform: scale(1) } 50% { transform: scale(1.1) } } then apply `animation: pulse 1.5s ease-in-out infinite;`' },
  { id: 'py-decorators', title: 'Write a Timing Decorator', language: 'Python', difficulty: 'Hard', minutes: 22, xp: 160, coins: 48, prompt: 'Write a decorator `@timed` that prints how long the wrapped function took to run.', solution: 'Wrap the function, record time.perf_counter() before and after the call, print the difference, and return the result.' },
  { id: 'js-async-await-errors', title: 'Error Handling with Async/Await', language: 'JavaScript', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Rewrite a `.then().catch()` fetch chain to use async/await with a try/catch block instead.', solution: 'try { const res = await fetch(url); const data = await res.json() } catch (err) { /* handle */ }' },
  { id: 'sql-group-by', title: 'Aggregating with GROUP BY', language: 'SQL', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Write a query that returns the total order count per customer, sorted from most to fewest orders.', solution: 'SELECT customer_id, COUNT(*) AS orders FROM orders GROUP BY customer_id ORDER BY orders DESC;' },
  { id: 'py-file-io', title: 'Reading and Writing Files', language: 'Python', difficulty: 'Easy', minutes: 10, xp: 80, coins: 22, prompt: 'Write a function that reads a text file, counts the number of lines, and writes that count to a new file.', solution: "with open(path) as f: lines = f.readlines()\nwith open(out, 'w') as f: f.write(str(len(lines)))" },
  { id: 'js-react-usestate', title: 'Your First useState Counter', language: 'JavaScript', difficulty: 'Easy', minutes: 10, xp: 80, coins: 22, prompt: 'Build a React counter component with increment and decrement buttons using useState.', solution: 'const [count, setCount] = useState(0); onClick handlers call setCount(c => c + 1) / setCount(c => c - 1).' },
  { id: 'css-variables-theme', title: 'Theming with CSS Variables', language: 'CSS', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Set up CSS custom properties for a light/dark theme that swap when a `.dark` class is added to <html>.', solution: ':root { --bg: white; } .dark { --bg: #111; } then use `background: var(--bg)` everywhere.' },
  { id: 'py-error-handling', title: 'Custom Exceptions', language: 'Python', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Define a custom `InsufficientFundsError` exception and raise it from a `withdraw()` function when the balance is too low.', solution: 'class InsufficientFundsError(Exception): pass — then `raise InsufficientFundsError("...")` when balance < amount.' },
  { id: 'js-array-sort-objects', title: 'Sorting Arrays of Objects', language: 'JavaScript', difficulty: 'Medium', minutes: 12, xp: 110, coins: 32, prompt: 'Sort an array of user objects by `age` ascending, then by `name` alphabetically for ties.', solution: 'users.sort((a, b) => a.age - b.age || a.name.localeCompare(b.name))' },
  { id: 'ts-interfaces', title: 'Modeling Data with Interfaces', language: 'TypeScript', difficulty: 'Easy', minutes: 12, xp: 100, coins: 28, prompt: 'Define a `User` interface with required `id`/`name` fields and an optional `email`, then write a function that accepts it.', solution: 'interface User { id: number; name: string; email?: string } — the `?` marks `email` as optional.' },
  { id: 'py-list-slicing', title: 'Mastering List Slicing', language: 'Python', difficulty: 'Easy', minutes: 8, xp: 70, coins: 20, prompt: 'Given a list, return every second element, then return the list reversed, both using slice syntax.', solution: 'items[::2] for every second element, items[::-1] to reverse — no loops needed.' },
  { id: 'js-local-storage', title: 'Persisting State with localStorage', language: 'JavaScript', difficulty: 'Easy', minutes: 10, xp: 80, coins: 22, prompt: 'Persist a to-do list to localStorage so it survives a page refresh, loading it back in on startup.', solution: 'localStorage.setItem("todos", JSON.stringify(todos)) on change; JSON.parse(localStorage.getItem("todos")) on load.' },
  { id: 'css-responsive-nav', title: 'Responsive Navigation Bar', language: 'CSS', difficulty: 'Medium', minutes: 18, xp: 130, coins: 38, prompt: 'Build a navbar that shows a horizontal menu on desktop and collapses into a hamburger toggle below 768px.', solution: 'Use a media query at 768px to hide the horizontal menu and show a toggle button that reveals a stacked menu.' },
  { id: 'py-oop-inheritance', title: 'Class Inheritance', language: 'Python', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Create a base `Animal` class with a `speak()` method, then override it in `Dog` and `Cat` subclasses.', solution: 'class Dog(Animal): def speak(self): return "Woof" — subclasses override the parent method with their own version.' },
  { id: 'js-fetch-pagination', title: 'Paginated API Fetching', language: 'JavaScript', difficulty: 'Hard', minutes: 25, xp: 170, coins: 50, prompt: 'Write a function that fetches all pages of a paginated API (which returns a `nextPage` URL) and combines the results.', solution: 'Loop: fetch current page, push its items, follow res.nextPage until it is null, then return the combined array.' },
  { id: 'sql-subqueries', title: 'Filtering with Subqueries', language: 'SQL', difficulty: 'Hard', minutes: 20, xp: 150, coins: 45, prompt: 'Write a query that returns customers who have placed more orders than the average customer.', solution: 'SELECT customer_id FROM orders GROUP BY customer_id HAVING COUNT(*) > (SELECT AVG(cnt) FROM (SELECT COUNT(*) cnt FROM orders GROUP BY customer_id) t);' },
  { id: 'py-context-managers', title: 'Custom Context Managers', language: 'Python', difficulty: 'Hard', minutes: 20, xp: 150, coins: 45, prompt: 'Write a context manager (using `with`) that times a block of code and prints the elapsed time on exit.', solution: 'Implement __enter__ to record the start time and __exit__ to print the elapsed time — or use @contextmanager with a yield.' },
  { id: 'js-array-flat', title: 'Flattening Nested Arrays', language: 'JavaScript', difficulty: 'Easy', minutes: 8, xp: 70, coins: 20, prompt: 'Flatten a deeply nested array of arrays into a single flat array.', solution: 'array.flat(Infinity) — flattens every level of nesting in one call.' },
  { id: 'css-transitions-hover', title: 'Smooth Hover Transitions', language: 'CSS', difficulty: 'Easy', minutes: 8, xp: 70, coins: 20, prompt: 'Add a smooth transition so a button lifts and changes shadow on hover, instead of snapping instantly.', solution: 'transition: transform .2s ease, box-shadow .2s ease; then define the :hover state changes — the transition animates between the two.' },
  { id: 'py-testing-basics', title: 'Writing Your First Unit Test', language: 'Python', difficulty: 'Medium', minutes: 15, xp: 120, coins: 35, prompt: 'Write a pytest test that verifies an `add(a, b)` function returns the correct sum for a few cases.', solution: 'def test_add(): assert add(2, 3) == 5 — pytest auto-discovers functions prefixed with `test_`.' },
  { id: 'js-react-usememo', title: 'Optimizing with useMemo', language: 'JavaScript', difficulty: 'Hard', minutes: 20, xp: 150, coins: 45, prompt: 'Given a component that recomputes an expensive filtered list on every render, wrap it in useMemo so it only recomputes when the source data changes.', solution: 'const filtered = useMemo(() => data.filter(expensiveCheck), [data]) — recalculates only when `data` changes.' },
  { id: 'sql-window-functions', title: 'Ranking Rows with Window Functions', language: 'SQL', difficulty: 'Hard', minutes: 22, xp: 160, coins: 48, prompt: 'Write a query that ranks products by sales within each category using a window function.', solution: 'SELECT *, RANK() OVER (PARTITION BY category ORDER BY sales DESC) AS rank FROM products;' },
  { id: 'py-async-basics', title: 'Async/Await in Python', language: 'Python', difficulty: 'Hard', minutes: 20, xp: 150, coins: 45, prompt: 'Write two async functions that fetch data concurrently using `asyncio.gather`, instead of awaiting them one at a time.', solution: 'results = await asyncio.gather(fetch_a(), fetch_b()) — both coroutines run concurrently, not sequentially.' },
  { id: 'js-template-literals', title: 'Multi-line Template Literals', language: 'JavaScript', difficulty: 'Easy', minutes: 6, xp: 60, coins: 15, prompt: 'Build an HTML string for a user card using a template literal with embedded variables, spanning multiple lines.', solution: '`<div>${user.name}</div>` — backticks allow embedded ${expressions} and literal newlines.' },
  { id: 'css-clamp-typography', title: 'Fluid Typography with clamp()', language: 'CSS', difficulty: 'Medium', minutes: 12, xp: 110, coins: 32, prompt: 'Make a heading scale fluidly between mobile and desktop without a media query, using clamp().', solution: 'font-size: clamp(1.5rem, 4vw + 1rem, 3rem); — scales smoothly between the min and max bounds.' },
]

function dayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 0)
  const diff = date - start
  return Math.floor(diff / 86400000)
}

export function todayKey(date = new Date()) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}

export function getTodayChallenge(date = new Date()) {
  const index = dayOfYear(date) % CHALLENGES.length
  return CHALLENGES[index]
}
