import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
page.on('framenavigated', (frame) => {
  if (frame === page.mainFrame()) console.log('navigated ->', frame.url())
})
await page.goto('http://localhost:5183/account')
await page.click('.flex.gap-2 >> button:has-text("Sign up")')
await page.fill('input[type="text"][maxlength="30"]', 'Debug User4')
await page.fill('input[pattern="[A-Za-z0-9_]+"]', 'debuguser4')
await page.selectOption('select', '10')
await page.fill('input[type="password"]', 'pass1234')
await page.click('button:has-text("Create account")')
await page.waitForURL('**/profile')
console.log('--- about to logout via navbar ---')
await page.click('button[aria-haspopup="menu"]')
await page.waitForSelector('text=Logout')
await page.click('div[role="menu"] >> text=Logout')
await page.waitForTimeout(1000)
console.log('final', page.url())
await browser.close()
