import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
await page.goto('http://localhost:5183/account')
await page.click('.flex.gap-2 >> button:has-text("Sign up")')
await page.fill('input[type="text"][maxlength="30"]', 'Debug User3')
await page.fill('input[pattern="[A-Za-z0-9_]+"]', 'debuguser3')
await page.selectOption('select', '10')
await page.fill('input[type="password"]', 'pass1234')
await page.click('button:has-text("Create account")')
await page.waitForURL('**/profile')
// click the ProfilePage's own inline "Log out" button (not navbar dropdown)
await page.click('button:has-text("Log out")')
await page.waitForTimeout(800)
console.log('final url', page.url())
await browser.close()
